- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/BlockController.kt
* Streamlined the queries to use the same data object
* Included more info
closes: #13
---
> Updating Block queries

- .github/workflows/build.yml
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Update all Staking Validators, regardless, so we can pull in new ones as they come up.
closes: #25
---
> Fix Staking Validator Bug

- .github/workflows/build.yml
- database/src/main/resources/db/migration/V1_4__Add_tx_marker_join_.sql
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AttributeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AssetController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
- third_party/proto/provenance/marker/v1/marker.proto
- third_party/proto/provenance/marker/v1/proposals.proto
- third_party/proto/provenance/metadata/v1/contract.proto
- third_party/proto/provenance/metadata/v1/query.proto
- third_party/proto/provenance/metadata/v1/scope.proto
- third_party/proto/provenance/metadata/v1/specification.proto
- third_party/proto/provenance/metadata/v1/tx.proto
* Added additional protos
* Updated grpc calls to pull marker data from marker rather than bank
* Updated the clean up github action to pin to version 0.3.0
closes: #XXXX
---
> Updating asset APIs

- .github/workflows/docker.yml
> Update dockerfile location in action

- .dockerignore
- .github/workflows/docker.yml
> Removing docker build target

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_5__Add_tx_cache_index_.sql
* Because it makes things happier
* Because it makes things happier
closes: #XXXX
---
> Adding index on tx_cache.height

- database/src/main/resources/db/migration/V1_6__Add_indices.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
* Also reworked the transaction queries to actually be more speedy.
* Tested against the working pio-testnet-1 db
closes: #XXXX
---
> Adding additional indices

- CHANGELOG.md
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/io/provenance/DownloadProtosPlugin.kt
- buildSrc/src/main/kotlin/io/provenance/DownloadProtosTask.kt
- proto/README.md
- proto/build.gradle.kts
- scripts/copy_proto_v2.sh
- third_party/proto/confio/proofs.proto
- third_party/proto/cosmos/tx/v1beta1/service.proto
Instead of an external (to gradle and the build environment, at least) shell script to download 3rd party
protos, this request utilizes a custom gradle plugin task.
---
> Custom Proto Plugin Task to Download 3rd Party Protos

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_7__Modify_for_min_gas_fee.sql
- docker/db-init/db-init.sql
- service/src/main/kotlin/io/provenance/explorer/config/Properties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ErrorFinding.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
- service/src/test/resources/application-test.properties
* Now deriving min gas fees from given transaction numbers
* Added scheduled task to calculate daily min/max/avg values
* Added APIs to get those values
* Updated Validator.bond_height to come from real numbers
* Added Asset status to the asset objects
* Added current gas fee to Validator objects
* Added migration to add in new data points
* Added migration to find common errors (tx counts dont add up, unknown msg types)
* Fixed bug with txs not being all downloaded
* I hate dates
closes: #30
---
> Make gas fees configurable

- .github/CODEOWNERS
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* Forgot a couple places to add a proposer record
* Reverted a change to the SpotlightCache entity type
closes: #XXXX
---
> Bug Fixing

- .github/workflows/docker-branch-delete.yml
- .github/workflows/docker.yml
* Allowing docker builds on branches -> useful for testing
* Adding delete docker image workflow for when a branch not main is deleted
---
> Updating docker workflows

- .github/workflows/docker-branch-delete.yml
* Using the wrong version, fixed.
---
> Fix version on delete docker gha

- .github/workflows/docker-branch-delete.yml
* Because variables are hard
closes: #XXXX
---
> Updating delete-docker wf

- .github/workflows/docker-branch-delete.yml
testing JWT token creation for docker deletion
closes: #XXXX
---
> Testing JWT token

- .github/workflows/docker-branch-delete.yml
* Is not currently viable with our auth setup on dockerhub.
* See: https://github.com/docker/roadmap/issues/115
closes: #XXXX
---
> Removing docker delete ghw

- .github/workflows/docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
* updated docker build to exclude release and tagged branches, and include tags
* Added release action to automate release
closes: #58
> Adding GHA for release process

- .github/workflows/docker.yml
- .github/workflows/release.yml
- CHANGELOG.md
- CONTRIBUTING.md
- scripts/linkify.py
Updating changelog for version v1.0.0
---
> Update changelog for v1.0.0

- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* on asset list and asset detail, the supply object now contains initial and circulation rather than circulation and total.
* All coin objects (with a balance and a denom) now have a queryDenom value to be used for querying based on that denom
* /api/v2/assets/{id}/holders now returns a paginated list
* asset supply total comes from bank module, and supply on asset detail object is now labelled as initial supply
closes: #52
---
> Update Asset things

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
* Now updating accout signatures when updating accounts
closes: #63
---
> Update Account signatures

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_10__Add_tx_join_indices.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/BlockController.kt
* Adding more indicies due to how the queries are being joined and searched
* Adding tx/msg checks to block look up and tx look up
* Allows for missed txs/msgs to be added under the hood
closes: #71
---
> Fixing Tx Query issues

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- proto/README.md
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- third_party/proto/provenance/marker/v1/marker.proto
- third_party/proto/provenance/metadata/v1/p8e/p8e.proto
- third_party/proto/provenance/metadata/v1/tx.proto
- third_party/proto/provenance/name/v1/name.proto
* Removed the offending function and replaced the count with the pagination.total count
* Updated prov protos to 1.2.0
closes: #79
closes: #80
---
> Asset Holder count bug

- CHANGELOG.md
- CONTRIBUTING.md
> Release v1.2.0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
* For ModuleAccount type, populate accountName on AccountDetail object
closes: #83
---
> Add name to Account

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_11__Add_marker_supply.sql
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AssetController.kt
* Added pagination to getAssets()
* Updated marker_cache table to store the current supply and latest tx timestamp
closes: #78
---
> Paginate Asset List

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_12__Update_account.sql
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* Fixed where syncing was erroring out because an account did not exist on chain yet
* Fixed where attribute msgs were assumed to belong to denoms
* Fixed where set metadata msg was pulling all denom names rather that base denom only
* Fixed where a block's validator list was incorrect
* Added missing IBC Header proto
* Updated tx type list to group IBC types together
closes: #85
closes: #91
closes: #93
---
> Allow unknown accounts

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AccountController.kt
* Added account queries for delegations, unbonding delegations, redelegations, and rewards
* this uses the account address as the "delegator"
closes: #96
---
> Add Account delegation query APIs

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
* Removed nhash conversion from backend. This will now be done by frontend.
* Removed queryDenom from CoinStr object
* API to fetch metadata for a denom already exists
closes: #66
---
> Removing nhash conversion 

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
Reverts provenance-io/explorer-service#99
> Revert "Removing nhash conversion "

- CHANGELOG.md
- TODO.md
- database/src/main/resources/db/migration/V1_13__Add_nft_tables.sql
- proto/README.md
- scripts/linkify.py
- service/src/main/kotlin/io/provenance/explorer/domain/core/Bech32.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/MetadataAddress.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Nfts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/exceptions/AddressFormatException.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/NftModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MetadataGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/NftService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NftController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Added some NFT APIs to start getting a feel of what that might look like
* Added a db migration to allow for scope ingestion
* Added running todo list
* Added MetadataAddress conversion class
* Updated tx processing to include NFTs
* fees are big, too big for int. using bigint
* Updated tx type listings
* Updated nft caching to pull correct data for contract spec msgs
* Tx Types are now sorted by module/type
refs: #29
---
> Add NFT APIs

- CHANGELOG.md
- TODO.md
- service/src/main/kotlin/io/provenance/explorer/domain/core/MetadataAddress.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Nfts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/NftModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AttributeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MetadataGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/ValidatorGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/NftService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NftController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* Now pulling asset supply on asset detail from correct source
* Now properly distincting txs in tx listview with filter
* Added Scope listview, Scope Detail, Scope Records API
* Fixed Accounts/delegations api from 500
* Now updating accounts with complete info
closes: #29
closes: #105
closes: #106
closes: #107
closes: #108
---
> NFT APIs and bug fixes

- CHANGELOG.md
- CONTRIBUTING.md
> Release v1.5.0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
* Removed nhash conversion from backend. This will now be done by frontend.
* Removed queryDenom from CoinStr object
* API to fetch metadata for a denom already exists
closes: #66
---
> Removing nhash conversion

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_14__Update_validator_cache.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* For whatever reason, programmatic sorting wasnt working.
* Added tokenCount to staking_validator_cache for sorting purposes
closes #112
---
> Properly sorting Validator Listview

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AccountController.kt
* They were not actually paginated. They are now.
closes #102
---
> Paginate Account Balances

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/web/v2/NftController.kt
* Removed due to massive performance issues
closes: #118
---
> Removing `nft/scope/all`

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/config/GlobalControllerAdvice.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Standardized failure statuses to return 404s when the requested id/address is incorrect
* can return message if error coming from chain query
* Filtering out blanks when associating addresses to txs
* Fixed boolean check on NFT delete messages
* Added an address check on unknown accounts being requested -> checking for proper address prefix
closes: #120
---
> Standardizing API failure statuses

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/io/provenance/DownloadProtosTask.kt
- proto/README.md
* Updated to Prov 1.4.1
* Updated to cosmos sdk 0.42.5
closes: #128
---
> Updating proto versions

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_18__Add_ibc_ledger.sql
- docs/ibc/Ledger.md
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Ibc.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/GovModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/IbcModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/IbcController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* Added APIs
* `/ibc/channels/balances` -> `/ibc/balances/channel` -> Balances broken down by chain/channel/denom
* `/ibc/balances/chain` -> Balances broken down by chain/denom
* `/ibc/balances/denom` -> Balances broken down by denom
* Added migration to hold ledger data
closes: #132
---
> IBC Ledger API

- CHANGELOG.md
- docs/ibc/Ledger.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AttributeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AccountController.kt
* Added API for Names owned by an address
* `/accounts/{address}/attributes/owned`
* Updated `/accounts/{address}` to include assigned attributes
* Added translation function to make the response more user-friendly
closes: #92
---
> Account Attributes

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Updated `AssetDetail.supply` from String to CoinStr
* Updated `AssetHolder.balance` to include `denom`
* Using actualy current height instead of deriving from signing infos
closes: #137
---
> Adding denom to counts

- .github/CODEOWNERS
- CHANGELOG.md
- database/src/main/resources/db/migration/V1_19__Add_missed_blocks.sql
- docs/validators/Missed_Blocks.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
* Due to how missed blocks is calculated for a validator, we need to be storing records of missed blocks to get an accurate count.
* Updated MsgConverter `typeUrl.contains()` to `typeUrl.endsWith()` due to some msgs containing names of other msgs
closes: #136
---
> Updating Missed blocks to pull from DB

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Removed list of tx msgs from TxSummary and TxDetail due to slowness with large lists
* Moved msgs into a separate API call
* `/api/v2/txs/{hash}/msgs?page={page}&count={count}`
closes: #142
---
> HOTFIX: Tx Msg

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/NftService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Added `msgType={msgType}` to `/api/v2/txs/{hash}/msgs` to allow for filtering based on `msgType`
* Added `/api/v2/txs/types/tx/{hash}` to fetch msg types applicable to a single tx
* Added `PagedResults.total` to return total record count
closes: #146
---
> Return msg count and allow msg filtering on tx detail page

- CHANGELOG.md
- docs/nft/NFTs.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/NftService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NftController.kt
* Updated `/api/v2/accounts/{address}` to return `TokenCount` object #140
* Shows count of fungible and non-fungible tokens
* Updated `/api/v2/nft/scope/owner/{address}` to return a listview rather than list of `Scope.uuid` #140
* Updated `NFTs.md` design doc to match newer design doc layouts
closes: #140
---
> Add NFT count to Account Detail

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
* Updated the MissedBlocks insert to accommodate out-of-sequence block heights
* allows for service catch up without compromising the missed blocks running totals
closes: #143
---
> Update Missed Blocks async to be more robust

- CONTRIBUTING.md
- docs/architecture/README.md
We currently don't have a place for ADRs to be put and have broken links in our documentation.
closes: #158 
---
> Add documentation for ADRs

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
We added a try catch around the validator to fail gracefully if the validator isn't returned
closes: #156 
---
> Fixed wrong error message being populated on commission when an operator is jailed

- docs/architecture/README.md
There is a typeo in the readme from a copy paste mistake that needs to be fixed.
---
> Fix a typeo in README

- .github/CODEOWNERS
> Add Fred and Ergels to codeowners

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
* Missed the processing step when adding the new protos from 1.5.0
closes: #169
---
> Processing newly added protos

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
> Bug: Don't try to save missed blocks when current block height is 0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
> Updating proposal status daily

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Fixed the listview to have default values for missing signing info
* Fixed the detail page to have default values for missing signing info
* Fixed an NPE on .toObjectNode() extension
closes: #178
closes: #180
---
> Fix 404 on validator listview filtered to Candidate

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_21__Add_tx_history_materialized_views.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/DbExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
Added Materialized views for `DAY` and `HOUR` to help with Tx History Graph with initial load time on the `14 Day Transaction History` graph on the [Dashboard](https://explorer.provenance.io/dashboard)
The views get refreshed when a block is written to the `block_cache` table. See:
* [Blocks.kt](https://github.com/provenance-io/explorer-service/blob/265aefaeee313f6b43eabfd728aaaeed812008c0/service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt#L65:#L101)
* [V1_21__Add_tx_history_materialized_views.sql](https://github.com/provenance-io/explorer-service/blob/265aefaeee313f6b43eabfd728aaaeed812008c0/database/src/main/resources/db/migration/V1_21__Add_tx_history_materialized_views.sql)
closes: #117 
---
Before we can merge this PR, please make sure that all the following …
> Mv tx history cnt to db table

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/GovModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Adding API at `/api/v2/txs/module/gov?address={address}&etc...`
* Returns specific governance data not usually found in tx listviews
* Moved the tx history materialized view refresh to the end of the async task
closes: #193
---
> Add Dedicated Gov Tx API

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
* Ensure governance proposal votes take precedence by block height
---
> Bug: Fix Gov vote record

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Was using count from page of validators, not count of all validators in the filter.
closes: #201
---
> Use actual count of validator list for page count

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_25__Combine_daily_hourly_gas_fee_stats_procudures.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- Combined `daily` and `hourly` stored procedures into one and set `processed = true` once `daily` and `hourly` aggregates are complete
- Updated code to call new procedure.
closes: #210 
---
> fixed update of the daily gas stats causes hourly data to be missed #210

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_26__Add_gas_fee_volumes.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
* Implemented daily and hourly gas fee volume.
* Added endpoint /gas/volume to retrieve gas fee volume
* Added tables:
* `tx_gas_fee_volume_day`
* `tx_gas_fee_volume_hour`
* Added stored procedure:
* `update_gas_fee_volume`
closes: #186 
---
> implement gas fee daily/hourly volumes #186

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* Heatmap API endpoint `/api/v2/txs/heatmap` for when Txs are submitted during the day.
closes: #187 
---
> implement heatmap #187

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/SupplyModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BankGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenSupplyService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
Implement Token statistics:
* Circulation supply
* Community Pool
* Bonded supply
closes: #188 
---
> Circulation community pool bonded supply

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Added support to fetch a validator's profile image from Keybase using their identity value
closes: #200
---
> Add Keybase support for validator icons

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_26__Add_gas_fee_volumes.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
* fee amount and gas wanted can be null on tx objects. Should account for that
---
> Fix nullable fields in Migration 26

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_27__Add_token_distribution_stats.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AssetController.kt
- service/src/main/resources/logback.xml
* Implement distribution of hash between sets of accounts statistics.
closes: #189 
---
> distribution of hash between sets of acounts #189

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_29__Modify_staking_validator.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/DbExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* No longer updates, now append-only
* Reworked how fetch validators APIs are being run to be more efficient
closes: #222
---
> Reworked validator state

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_30__Modify_block_proposer.sql
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/service/CacheService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* More efficient processing/querying
* Added block_latency to block_proposer
* useful for future APIs, less expensive than on-the-spot calcs
closes: #221
---
> Update spotlight_cache to append-only

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BlockGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
* Added block latency api for validator
* Added vote and proposer data for validator at height set
* Fixed validator votes vs validator set for spotlight data
closes: #199
closes: #183
---
> Added Block latency api, validator votes at height

- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
> Updating to cron to every 5 seconds

- CHANGELOG.md
> Release v2.3.1

- CHANGELOG.md
> Rerelease v2.4.0

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_32__Add_tx_retry_table.sql
- service/src/main/kotlin/io/provenance/explorer/Application.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt
* Sometimes txs just dont come back from the query when they should.
* Added a retry table to try again without having to manually do it
closes: #232
---
> Add block tx retry table

- CHANGELOG.md
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/exceptions/TendermintApiException.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BlockGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Testing out Figment's node reliability
* Defaulting to Figment's url, if that fails use the standard query node
* Added properties `explorer.figment-apikey`, `explorer.figment-url`
closes: #231
---
> Using Figment API for getBlock(height) call

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/core/Hash.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/Numeric.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/SigExtenstions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
* Txs msg not have pubkeys attached
* Find missing signatures based on msg types within the tx
* Added utlity to update the exitsing txs without sigs
closes: #249
---
> Find missing signatures from Msg Type

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_38__Add_validator_state_function.sql
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/Array.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Added get_validator_list() function to calc proper validator state based on inputs
* Updated queries to pull from function
closes: #261
---
> Respect `max_validators` param for active validator set

- build.gradle.kts
- docker/docker-compose.yml
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/GovGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Added API to return a list of binary versions and upgrade heights for the chain
* Remediated the Log4j vuln
closes: #246
---
> Chain Upgrade height API

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_39__Add_fee_payer_tables.sql
- docs/txs/Feepayer.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/TransactionJoins.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/UtilityController.kt
- service/src/main/resources/application-development.properties
* Added Feepayer.md doc
* Support for ingestion
* Added feepayer, updated fee on tx responses
closes: #252
---
> Adding tx fee, feepayer support

- CHANGELOG.md
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/Application.kt
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/config/SwaggerConfig.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/SigExtenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ParamModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/UtilityController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Added API for chain prefixes
* Updated the param set
* Added a property to disbale maintenance APIs
closes: #267
closes: #271
closes: #270
closes: #269
---
> Updating an account's public key to show the key, not the translated address

- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/config/SwaggerConfig.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Make swagger stuff via properties instead of hardcoding
---
> Swagger URL update

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BlockGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
* Needed to get all validators regardless of status for limited data
closes: #282
---
> Adding abbreviated validator query for FE

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
> Allow null prices for unknown asset pricing

- docker/docker-compose-db.yml
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
* Found through a fresh DB start, a minor fix to allow tx fees to save properly
* Found through a fresh DB start, a minor fix to allow tx fees to save properly
---
> Minor fixes

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_40__Data cleanup.sql
- database/src/main/resources/db/migration/V1_41__Add_ingestion_procedures.sql
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/TableObjects.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Ibc.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Signatures.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/TransactionJoins.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/CacheService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/BlockController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/UtilityController.kt
* Reworked block/transaction ingestion
* Created procedures to save all block/ tx data at once
* Should eliminate rogue data insertion
* Migration 1.40 - Data clean up
* Removed duplicate data for `tx_message`, `tx_msg_event`, `tx_msg_event_attr`
* Migration 1.41 - Added ingestion procedures
* Added unique indices for all tx-related tables
* Added types `tx_event`, `tx_msg`, `tx_update`, `block_update`
* Added procedures `add_tx(tx_update, integer, timestamp)`, `add_block(block_update)`
* Updated `tx_msg_event_attr` with `attr_idx`, `attr_hash`; updated new columns with data
closes: #274
---
> Ingest Rework

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_42__Invalid_denom_cleanup.sql
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
* Updated unknown denom insertion to use status MARKER_STATUS_UNSPECIFIED
* So they dont show up in the asset listview
closes: #289
---
> Invalid Denom cleanup

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_41__Add_ingestion_procedures.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/MessageTranslationExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ParamModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BankGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenSupplyService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
* Added value rollups to delegation/redelegation/unbonding APIS for both Accounts and Validators
* Generic map to add different values for different PagedResults responses as needed
* General cleanup of APIs
* Updated token stats to use correct Bonded value
* Updated params to represent percentage values better
* Updated Migration 1.41 to include exception handling in procedures
* Updated BlockRetry to use the main block insertion method rather than the intermediary
closes: #290
---
> Add rollup map to PagedResults response

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_41__Update_tx_event_attr_table.sql
- database/src/main/resources/db/migration/V1_42__Update_tx_event_attr_part_1.sql
- database/src/main/resources/db/migration/V1_43__Update_tx_event_attr_part_2.sql
- database/src/main/resources/db/migration/V1_44__Add_ingestion_procedures.sql
- database/src/main/resources/db/migration/V1_45__Invalid_denom_cleanup.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/resources/application.properties
When the insertion procedure failed, the catch insertion of a retry record was failing for a different reason. This fixes that issue.
Also makes migrations easier to track and separate on failure. 
---
> Fixing tx failure due to Postgres Transaction context overlap

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_46__Update_ingestion_procedure.sql
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/Application.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/TableObjects.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Ibc.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/IbcModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/BlockGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/ValidatorGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/resources/application-development.properties
* Updated BlockRetry to use the main block insertion method rather than the intermediary, added exception handling
* Fixed the ingestion procedure re: `signature_join` data
* Migration 1.46 - Update Ingestion procedure
* Fixed signature_join insertion to use the correct join key value
* Added `denom_trace` to IBC balance objects
* Added error logging to pricing engine calls
* Added `24 Hr Power Change` to the Validator listview response
closes: #277
---
> 24hr validator delegation changes

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_47__Add_asset_pricing.sql
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/Application.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/CacheService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* Updated pricing engine calls to be async, pulling new values and saving
* Updated NHASH pricing to pull from gecko api
closes: #296
---
> Updated pricing engine calls

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Ibc.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
* Trying to insert a proposal monitor record was failing due to a value
---
> Hotfix - Proposal Monitor insert

- CHANGELOG.md
> Release 3.3.1 - Hotfix

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_42__Update_tx_event_attr_part_1.sql
- database/src/main/resources/db/migration/V1_43__Update_tx_event_attr_part_2.sql
> Hotfix - Fixing migrations to work on an empty DB

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_49__Add_validator_market_rate.sql
- database/src/main/resources/db/migration/V1_50__Update_tx_fee_records.sql
- docs/architecture/Statistic Breakdown.md
- docs/txs/Fee Breakdown.md
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/Upsert.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AssetController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
* Reworked Tx Fee calcs to align with how market rates are actually determined
* Added `validator_market_rate`
* Removed `min_gas_fee` from `block_proposer`
* Renamed `validator_gas_fee_cache` to `validator_market_rate_stats`
* Renamed `chain_gas_fee_cache` to `chain_market_rate_stats`
* Added generic batch upsert functionality
* Expanded top 5 accounts on token distribution list
* Updated API naming to reflect current state
* Added doc to track all the statistics being presented
Gods I hope this is right...
closes: #XXXX
---
> TX Fee rework - Again

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
> Market Rate API

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_51__Update_ingest_procedure.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
> Hotfix, cuz of course

- CHANGELOG.md
> Release 3.4.1

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_52__Create_all_validator_state_function.sql
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/Array.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/TransactionJoins.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
* Added API to calc uptimes for all active validators, and show missed block percentages
* Updated code to use a better query
closes: #260
---
> Adding validator uptime stats

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_53__Add_chain_AUM_table.sql
- docs/architecture/Statistic Breakdown.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
* API for Chain AUM over time
* returns as hourly records
* Updated docs
closes: #291
---
> Chain AUM time series

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_54__Modify_validator_state.sql
- database/src/main/resources/db/migration/V1_55__Add_debug_block_tx_procedures.sql
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/TableObjects.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorController.kt
* API to return commission history for a validator
closes: #300
---
> Valiator commission history

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_56__Add_tx_hash_id_to_gov_tables.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/TransactionJoins.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
* Now inserting `tx_sm_code` record when a SC code is identified and correlated with a governance proposal
* Added tx_hash_id to governance tables
closes: #319
---
> SC code txs via governance proposal

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_57__Add_marker_unit_table.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AssetController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
* Updated nhash unit pricing to pull from pricing engine
* Made the pricing calcs uniform
* Added the ability to search for a denom by any of its units
closes: #321
---
> Updating denom unit pricing

- CHANGELOG.md
> Release 4.1.0

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_58__Add_weight_to_proposal_votes.sql
- database/src/main/resources/db/migration/V1_59__Add_cache_update_for_processing.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/GovModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/CacheService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* Now handling weighted votes
* Updated some calls to handle for an empty DB
* Broke out insert pieces from `add_tx()` function into their own routines for better support
closes: #323
---
> Weighted votes

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
> Fixed validators at height pagination bug

- .dockerignore
- docker/Dockerfile-service
- docker/service-configure
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/GovGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* Fixing when a proposal fails a deposit period.
* dockerfile changes - Includes support for vault implementation for secret keeping
closes: #330
Signed-off-by: Carolyn Russell <cj.russell7601@gmail.com>
---
> Fixing proposal updates

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/UtilityController.kt
* Incorrect mapNotNull() usage caused mismatched indices during ibc msg processing.
closes: #331
---
> Fixing IBC msg processing

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_61__Update_ibc_ledger.sql
- database/src/main/resources/db/migration/V1_62__Update_tx_ingest_for_ibc.sql
- docker/docker-compose-db.yml
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Ibc.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/TransactionJoins.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/IbcModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Helper.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/IbcController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/SmartContractController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
- service/src/main/resources/application-development.properties
* IBC flows work differently than we had originally thought. These changes account for duplicate response msgs coming from a relayer, in addition to updates to the events coming from a successful tx
* Adds scraping for relayer association, ibc tx links
* Adds new APIs for ibc relayers per channel, txs per IBC chain, channel
closes: #336
---
> Fixing IBC Ingestion

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenSupplyService.kt
> Removing zero-sequenced acocunt balances from circulation total

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_63__Add_uuid_or_null_function.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/SmartContracts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/SmartContractModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/SmartContractService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/SmartContractController.kt
* Added filters on creator, has_contracts to code listview
* Added filters on creator, admin, label to contract listview
* Added filters on creator, admin to contracts by code listview
* Added API to fetch unique non-UUID contract labels
closes: #339
---
> Add filtering params to SC code and contract listview queries

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/NotificationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NotificationController.kt
* As requested
closes: #XXXX
---
> Add Announcement API getById

- CHANGELOG.md
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/resources/application-development.properties
* The github API has a default limit on records from the release query. Updated to include count and page.
* Updated Pricing Engine API pathing
closes: #349
---
> Fixing Upgrades fetch failure

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Notifications.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/NotificationModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/NotificationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NotificationController.kt
* Actually paginated the list call
* Added next, prev ids to responses
---
> Announcement tweaks

- .github/CODEOWNERS
- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Notifications.kt
* adding Jarryd as a codeowner
---
> Fixing announcement by id bug

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/ValidatorGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
* Now returning all signing infos from the query
* Recalced missed blocks from correct values
closes: #352
---
> Fixing Validator missed blocks, bond height bug

- CHANGELOG.md
- CONTRIBUTING.md
> Release 4.2.0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/NotificationService.kt
> Bug fix Upgrade Announcement mismatch

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/NotificationService.kt
Reverts provenance-io/explorer-service#358
> Revert "Bug fix Upgrade Announcement mismatch"

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
> Fixed Validator missed block count

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_65__Add_naming_tree.sql
- docker/docker-compose-db.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Name.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/DbExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/NameModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AttributeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/NameService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/MigrationService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/NameController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/MigrationController.kt
* Added naming tree API, ingestion
closes: #134
---
> Add Naming tree

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
> Hotfix: Addresses not always being associated with a tx

- service/src/main/kotlin/io/provenance/explorer/grpc/v1/GovGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/NotificationService.kt
> Fixing Scheduled Upgrades announcement

- CHANGELOG.md
- CONTRIBUTING.md
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
> Hotfix - Recvs in same block, different Txs

- CHANGELOG.md
- docker/docker-compose-db.yml
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/ProtoExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AttributeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/AccountControllerV2.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt
- service/src/main/resources/application-development.properties
* New API set to accommodate additional vesting info
* Ingestion support
closes: #366 
---
> Vesting Account updates

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_66__Update_tx_fee.sql
- docs/txs/Fee Breakdown.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Helper.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MarkerGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/UtilityController.kt
* Ingests custom msg fees from wasm txs
* Saves the OG fee amount and type for historical purposes
closes: #367
---
> Provwasm related updates

- database/src/main/resources/db/migration/V1_66__Update_tx_fee.sql
> Fixing DB migration

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/MsgCreationModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
* Swapped `Long` for `BigDecimal` in places that will need it, specifically for large nhash quantities
* Should fix the Rich List issue
* Now rounding circulating supply, community pool values as those are whole `nhash` values
closes: #380
closes: #381
---
> Swapping Long to BigDecimal

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
> Fixing error on reading EventFee object

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_67__Add_cmc_caching.sql
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TokenModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/TokenController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Added ingestion for CMC pricing data
* Added APIs to expose that data
closes: #388
---
> Adding CMC API support

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_68__Update_tx_fee_again.sql
- database/src/main/resources/db/migration/V1_69__Update_tx_hash_uniqueness.sql
- database/src/main/resources/db/migration/V1_70__Fix_fee_records.sql
- docker/docker-compose-db.yml
- docs/txs/Fee Breakdown.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/SmartContracts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/FeeExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MsgFeeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionController.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt
* Added an API to check account balances at height
* Fixed how fees were being calc'd/ found for txs, both success and failure
* Added uniqueness on height/ hash for dupe tx hashes
closes: #387
closes: #384
---
> Fix failed tx fee calcs, and added support for dupe tx hashes

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/IbcGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/test/kotlin/io/provenance/explorer/domain/ExtensionsTest.kt
> Updating Prov dependency to 1.12.0

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_71__Update_rollup_functions.sql
- database/src/main/resources/db/migration/V1_72__Update_validator_state.sql
- database/src/main/resources/db/migration/V1_73__Add_keybase_image_cache.sql
- docker/docker-compose-db.yml
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/config/GlobalControllerAdvice.kt
- service/src/main/kotlin/io/provenance/explorer/config/SwaggerConfig.kt
- service/src/main/kotlin/io/provenance/explorer/config/interceptor/JwtInterceptor.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/SmartContracts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Validators.kt
- service/src/main/kotlin/io/provenance/explorer/domain/exceptions/InvalidJwtException.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/FeeExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ValidatorModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MsgFeeGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/ValidatorGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/utility/UtilityController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* Added proper exception for JWT token errors
* Added fix for fee bug on success, for 1.11 block range
* Now handling validator states that disappear due to 0 delegations
* Now caching Keybase img urls against addresses
* Added async to reprocess blocks in the 1.11 period behind the scenes
closes: #394
closes: #395
closes: #396
closes: #397
---
> Various bug fixes

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/config/GlobalControllerAdvice.kt
- service/src/main/kotlin/io/provenance/explorer/config/SwaggerConfig.kt
- service/src/main/kotlin/io/provenance/explorer/config/interceptor/JwtInterceptor.kt
- service/src/main/kotlin/io/provenance/explorer/domain/exceptions/TendermintApiException.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/ProtoExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/GrantsModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AuthzGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/FeegrantGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GrantService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/GrantsController.kt
* Added APIS to return list for authz grants for the address as granter or grantee
* Added APIS to return list for feegrant allowances for the address as granter or grantee
* Applies to all valid standard addresses (including contracts)
closes: #265
---
> Adding APIs for Authz grants and Feegrant allowances

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
* Added the ability to include additional msg types in the module type list
* Applied to the ASSET and TRANSFER modules for now
closes: #405
---
> Update the txs lists on the asset page

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_74__Update_known_ibc_denoms.sql
- database/src/main/resources/db/migration/V1_75__Add_function_for_associated_addresses.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
* Added function get_tx_associated_values()
* Updated known IBC denoms
closes: #340
---
> Adding associated value map to tx detail

- CHANGELOG.md
> Release 5.1.0

- CHANGELOG.md
- docker/docker-compose.yml
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/FeeExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/PricingService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/TokenController.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
* moved to an ENV to better prepare for private networks
closes: #399
---
> Extract `nhash` as utility token into configurable ENV

- service/src/main/kotlin/io/provenance/explorer/config/SwaggerConfig.kt
- service/src/main/kotlin/io/provenance/explorer/config/interceptor/JwtInterceptor.kt
> Moving from BearerToken to Authorization for Cors reasons

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/PricingService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt
* Additional API to get account balance for the defined utility token in the service
closes: #418
---
> Adding API to get account balance for single denom

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/FeeExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
* fix fee calc for success without msg fees
---
> Hotfix - Fee calcs, again.

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
[
closes: #XXXX](closes: #424)
---
> Fix bug where weighted vote values were being exponentialized

- CHANGELOG.md
> Release v5.2.0

- CHANGELOG.md
> Release v5.2.1

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_82__Add_tx_signature_table.sql
- database/src/main/resources/db/migration/V1_83__Update_ingest_procedures_for_sigs.sql
- docs/txs/Signatures.md
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Signatures.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/SigExtenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/CommonModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/SignatureModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Helper.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/IbcService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt
- service/src/test/kotlin/io/provenance/explorer/domain/ExtensionsTest.kt
* Improved ingestion on tx signatures, account signatures
* Better tracking of idx, sequence on tx sigs
* Better response objects containing sig info for txs, accounts
closes: #416
---
> Signature updates

- CHANGELOG.md
- RELEASE_CHANGELOG.md
- database/src/main/resources/db/migration/V1_82__Update_incorrect_fees.sql
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
> Release v5.2.2

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_85__Add_msg_subtypes.sql
- service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/Array.kt
- service/src/main/kotlin/io/provenance/explorer/domain/core/sql/QueryFunctions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Governance.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/AccountGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
- service/src/main/kotlin/io/provenance/explorer/service/utility/UtilityService.kt
* Grant, Exec, and Revoke all have a subtype(s) within them. Its super useful to be able to see what those types are.
* Fixed Account tx history response to actually respond with something
* Fixed proposal `eligibileAmount` for quorum percentages
* Fixed unending do-while loop on getting account balance for denom
closes: #417
closes: #431
closes: #432
closes: #433
---
> Exposing subtypes for certain msg types, other fixes

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/CoinExtensions.kt
> Release v5.3.0

- CHANGELOG.md
> Release v5.3.1

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_83__Add_tx_signature_table.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
> Signature migration hotfix

- CHANGELOG.md
> Release 5.3.2

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt
* Allows for checking without pulling all the data
closes: #447
---
> Add API to return Account flags

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/MessageTranslationExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TransactionModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
* Now returning objects including tx msg logs
* Now returning human-readable objects for Tx-level events
closes: #400
closes: #401
---
> Add Tx Msg and Tx-level logs

- CHANGELOG.md
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- database/src/main/resources/db/migration/V1_86__Account_token_counts.sql
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Accounts.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Name.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Notifications.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/AssetModels.kt
- service/src/main/kotlin/io/provenance/explorer/grpc/v1/MetadataGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
- service/src/main/kotlin/io/provenance/explorer/service/PricingService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
* Caching due to some super long-running queries to get the values
closes: #448
---
> Cache FT/NFT counts

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TokenModels.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/TxHistoryDataViewModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/TokenController.kt
> Add CSV download for hash price history chart

- service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Helper.kt
- service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
> 1.13 followup

- .github/workflows/publish.yml
> Publish fix

- docker/Dockerfile-service
- settings.gradle.kts
> Updating dockerfile

- .github/workflows/publish.yml
> Publishing fixes

- .github/workflows/publish.yml
> Publish fixes 2

- .github/workflows/publish.yml
> Publish fixes 3

- api-client/README.md
- api-client/build.gradle.kts
> publish fixes 4

- api-client/README.md
- api-client/build.gradle.kts
- api-model/README.md
- service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
* Updated READMEs
* Added groups msg types to the serializer
---
> Various updates

- .github/workflows/publish.yml
> Trigger correctly

- .github/workflows/release.yml
- CHANGELOG.md
> Release 5.4.0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/FeeExtensions.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/ValidatorControllerV3.kt
* Also fix no fee amount passed in
---
> Fix validator v3 api

- .github/workflows/ktlint.yml
- CHANGELOG.md
- README.md
- api-model/src/main/kotlin/io/provenance/explorer/model/base/CommonModels.kt
- build.gradle.kts
- docker/Dockerfile-service
- service/build.gradle.kts
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
- service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
- service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
- service/src/main/kotlin/io/provenance/explorer/web/v2/TransactionControllerV2.kt
- service/src/main/kotlin/io/provenance/explorer/web/v3/TransactionControllerV3.kt
> Adding params to heatmap API

- CHANGELOG.md
- api-client/src/main/kotlin/io/provenance/explorer/client/AccountClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/AssetClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/BaseClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/BlockClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/GeneralClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/GovernanceClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/GrantsClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/IbcClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/NameClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/NftClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/SmartContractClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/TokenClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/TransactionClient.kt
- api-client/src/main/kotlin/io/provenance/explorer/client/ValidatorClient.kt
Adds query parameters to the feign clients and allows for specifying the object mapper. 
Note that the object mapper must include the `kotlinModule()` in order to deserialized correctly. Some of the clients also include the joda time library, which would also need to be included in the object mapper for those requests.
closes: #487
---
- [n/a] Wrote unit and integration
> add query parameters to API client

- CHANGELOG.md
> Release 5.5.0

- CHANGELOG.md
- RELEASE_CHANGELOG.md
> Merge release v5.6.0 changelog to main 

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
Found a bug in dlob orderbooks that prevented saving correct information to database.  
Add missing change log entry.
Please review testnet explorer hash history from dates Aug 2nd to present. https://explorer.test.provenance.io/dashboard
closes: #496
---
> Rollup Start of day fix

- gradle.properties
Change developer id information to current developer.
closes: #XXXX
---
> Change pom developer id information

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
Update protos to 1.18.0-rc2.
closes: #510
---
> Update protos to 1.18.0-rc2

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
Update to final release v1.18.0 protos.
closes: #XXXX
---
> Update to protos v1.18.0

- CHANGELOG.md
- RELEASE_CHANGELOG.md
Update change log for main post release
closes: #XXXX
---
> Update changelog on main

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/test/kotlin/io/provenance/explorer/service/TokenServiceTest.kt
Osmosis now requires a `coinMinimalDenom` value to be included in the URL input for pricing. This PR adds the coinMinimalDenom parameter with the current nhash IBC denomination `ibc/CE5BFF1D9BADA03BB5CCA5F56939392A761B53A10FBD03B37506669C3218D3B2` for the Osmosis network.
closes: #XXXX
---
> Add new required value to osmosis pricing input

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
> Update provenance protos to v1.19.0

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/grpc/flow/FlowApiGrpcClient.kt
Keep alive time adjustment for flow api grpc connection.  Was set too low and getting this error: ```io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Connection closed after GOAWAY. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings```
closes: #XXXX
---
> Update grpc flow keepalive time

- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/grpc/flow/FlowApiGrpcClient.kt
- service/src/main/kotlin/io/provenance/explorer/service/AssetService.kt
Pagination was looping was incorrect.
closes: #XXXX
---
> Fix pagination for zero index flow api

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_93__Remove_columns_from_missed_block_table.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
> Remove `running_count` and `total_count` columns from the `missed_blocks` table

- .github/dependabot.yml
> Add dependabot config 

- .github/dependabot.yml
- .github/workflows/docker.yml
> Ignore dependabot branches for docker publishing

- CHANGELOG.md
- database/src/main/resources/db/migration/V1_95__Remove_asset_pricing_data_column.sql
- service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt
> Remove the `data` column from the `asset_pricing` table.

- CHANGELOG.md
- buildSrc/src/main/kotlin/Dependencies.kt
This PR upgrades the provenance protos to v1.20.1
closes: #XXXX
---
> Upgrade provenance protos to v1.20.1

- CHANGELOG.md
> - update changelog for v7

- CHANGELOG.md
- api-model/src/main/kotlin/io/provenance/explorer/model/GovernanceModels.kt
- service/src/main/kotlin/io/provenance/explorer/service/GovService.kt
Return title, summary, and metadata in gov prop header
---
> Return title, summary, and metadata in gov prop header

- service/src/main/kotlin/io/provenance/explorer/config/pulse/PulseProperties.kt
- service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/pulse/Enums.kt
- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/pulse/PulseMetric.kt
- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
- service/src/main/resources/application-container.properties
- service/src/main/resources/application-development.properties
Added Hash price metric. 
Optional env added to calculate private equity for known denoms and add to TVL metric.
Changed chain fees and transactions metrics to compute totals in a range span instead of fixed-daily or all-time totals.
---
> TVL and Hash Price Metric Updates

- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
Adds series data to display a line chart for TVL
closes: [FE #32](https://github.com/provenance-io/frontend-provenance-repulse/issues/32)
---
> Series data for TVL

- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
Fixes broken metrics from trying to read missing cache data
---
> Handle attempts to render series data before cache for the day is generated

- service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/pulse/Enums.kt
- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
Adds a 3 month/quarter timespan to MetricRangeType
closes: #XXXX
---
> Add a 3 month timespan

- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
Ok, trying again. This should show the relevant series data for each range
closes: #XXXX
---
> Fix series range caching

- service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
> Add functions for getting loan data over a range

- service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
- service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
- service/src/main/kotlin/io/provenance/explorer/service/async/ScheduledTaskService.kt
Switch to using nav_events for tx volume
> Pulse TX Summaries Fix
