CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt

* Now handling no rewards on a validator
* Added transaction context for address lookup for tx query
closes: #76
---

Fixing Mainnet bugs

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/entities/ErrorFinding.kt
service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt

* Fixed bug where the tx message type was being overwritten by "unknown"
---

Bug Fix: overwritten tx msg type

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
service/src/test/kotlin/io/provenance/explorer/domain/ExtensionsTest.kt

Created a method to get escrow account address for ibc transfers.  
This should be replaced with an grpc call once cosmos implements: [Issue: 9437](https://github.com/cosmos/cosmos-sdk/issues/9437)
closes: #119
---

Add domain extension to get escrow account address

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt

This addresses an issue where https://service-explorer.test.provenance.io/swagger-ui/index.html#/Validators/validatorsUsingGET was throwing a 500 in test if you set the status to anything other than active, due to a jailed operator.
---

Use a try catch block to avoid an error on jailed operators and default the value to 0

---

.gitignore
CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/Application.kt
service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt

Fix bug with MetadataAddress being printed as a Base64 string on the UI
The following files were modified:
- .gitignore
- CHANGELOG.md
- service/src/main/kotlin/io/provenance/explorer/Application.kt
- service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
closes: #145
---

Tx msg printed as base64

---

CHANGELOG.md
database/src/main/resources/db/migration/V1_24__Add_gas_fee_stats.sql
service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/ExplorerModels.kt
service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt
service/src/main/kotlin/io/provenance/explorer/web/v2/GeneralController.kt

- Created gas fee statistics tables for day/hour for transactions with single messages.
Design approach:
- Collect single message txs into a cache table `tx_single_message_cache`
- From `tx_single_message_cache`, aggregate `daily` and `hourly` data into `daily` and `hourly` tables.
- Create a `stored procedure` that will update aggregate data based on the `tx_timestamp` of the latest single message transaction. 
closes: #185 
---

add gas fee statistics per message type

---

CHANGELOG.md
database/src/main/resources/db/migration/V1_31__Modify_tx_message.sql
service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt
service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
service/src/main/kotlin/io/provenance/explorer/service/BlockService.kt
service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
service/src/main/kotlin/io/provenance/explorer/service/MigrationService.kt
service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCaching.kt
service/src/main/kotlin/io/provenance/explorer/web/v2/MigrationController.kt

* Unnecessary refreshes can bog down the db connections, forcing a service restart
* This should reduce the number of refreshes to the view, and locking of queries against the view
* Made TxMessageSingle cache entry insertIgnore
* Added migration API to fix tx_message.tx_message_hash
* Added migration 1.31 to add msg idx to tx_message table
* Allows for proper msg uniqueness due to same db hash value.
---

Bug Fixes: Adding additional check to refresh validator state view

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
service/src/main/kotlin/io/provenance/explorer/domain/entities/Name.kt
service/src/main/kotlin/io/provenance/explorer/domain/models/explorer/NameModels.kt
service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
service/src/main/kotlin/io/provenance/explorer/service/NameService.kt
service/src/main/kotlin/io/provenance/explorer/web/v2/AccountControllerV2.kt
service/src/main/kotlin/io/provenance/explorer/web/v2/NameController.kt

* Deprecated the accounts API to get names, and replaced with generic API to get owned names by address
* Applies to any standard address, including contracts
* Returns restriction and child count
closes: #346
---

Adding dedicated API to get attribute names by address

---

buildSrc/src/main/kotlin/Dependencies.kt

Update pio protos v1.17.0-rc1

---

database/src/main/resources/db/migration/V1_89__Delete_from_token_historical_daily.sql
service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
service/src/main/kotlin/io/provenance/explorer/service/TokenService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncService.kt

Aggregate new dlob orderbooks

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
service/src/test/kotlin/io/provenance/explorer/domain/extensions/ExtenstionsKtTest.kt

Error was caused by trying to convert a json object from a string that contained a string value that was also a json.  In this case, the memo field in an ibc packet contained json.
I added tests to confirm that a json that is formatted still passed worked.
closes: #501 
---

Error parsing ibc hooks memo object

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/grpc/extensions/MsgConverter.kt
service/src/main/kotlin/io/provenance/explorer/service/async/AsyncCachingV2.kt

There was a filtering of transactions that were not from the groups module and it would lose the index of the required event log index.  Fixed by returning a tuple with the expected index.
closes: #499 
---

Fix groups proposal error

---

CHANGELOG.md
buildSrc/src/main/kotlin/Dependencies.kt
service/build.gradle.kts
service/src/main/kotlin/io/provenance/explorer/config/RestConfig.kt
service/src/main/kotlin/io/provenance/explorer/service/GovService.kt

Dynamically add new provenances protos to JsonFormat.TypeRegistry

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClient.kt
service/src/test/kotlin/io/provenance/explorer/grpc/v1/TransactionGrpcClientTest.kt

This pull request updates the query format in the `getTxsEvent` method within the `TransactionGrpcClient` class to align with the latest protobuf definitions.
closes: #XXXX
---

Update grpc tx endpoint to use new query property

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/extensions/Extenstions.kt
service/src/main/kotlin/io/provenance/explorer/domain/extensions/MessageTranslationExtensions.kt
service/src/main/kotlin/io/provenance/explorer/service/TransactionService.kt
service/src/test/kotlin/io/provenance/explorer/domain/extensions/ExtenstionsKtTest.kt

After the release of Provenance version` v1.19.0-rc`, the transaction details page was broken due to changes in how events are encoded from Base64 to a string, causing an exception. The solution was to add a method to check if a string is Base64 and attempt to decode it. If decoding fails, the method returns the original string. This backwards compatibility is needed since the explorer has cached transactions with old Base64 strings from versions prior to `v1.19.0.`
Additionally, improved logging on the transaction endpoint was added to better debug future errors, providing visibility into any processing issues.
closes: #XXXX
---
checked off. If any of the checklist items are not applicable, please leave …

Fix tx details request

---

CONTRIBUTING.md

This PR gets rid of the Explorer name convention we've been using for release names. While it was a fun idea, it didn't really add any value and could even become a problem if we accidentally picked an explorer with a problematic past.
A few reasons for this change:
1. **Not Useful**: The Explorer names didn't end up being all that helpful in practice.
2. **Potential Risk**: There's a chance we could end up associating a release with an explorer who has some baggage, which we definitely want to avoid.
3. **Simplifying the Process**: With more continuous releases planned, this would just add unnecessary work without any real benefit.
closes: #XXXX
---
checked off. If any of the checklist items are not …

Remove adding a Release Name to releases

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt

This PR addresses an issue where some validators were returning up to 316k records, fetching and serializing all results into `MissedBlockRecords`, only to use the first record. This caused longer query times, unnecessary data transfer, and serialization overhead. The update optimizes performance by adding a limit to queries, reducing data processing and improving efficiency. Additionally, logging was added to warn if processing exceeds 1 second.
closes: #XXXX
---

Add limit of 1 to missing block queries

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/ScheduledTaskService.kt

This PR removes the logic for calculating running_count and total_count in the missed_blocks table. We no longer need to store these values in the database since they can be easily derived with a simple query when necessary.
Previously, the calculation of these values could take several minutes when a validator missed a block, especially with large datasets. Now, only the consensus_address and block_missed are stored, which eliminates that overhead. The counts were not used in any endpoints or elsewhere in the code, so this cleanup improves performance without affecting functionality.
closes: #XXXX
---
write a little note …

Remove the logic for calculating `running_count` and `total_count` in the `missed_blocks`

---

CHANGELOG.md
database/src/main/resources/db/migration/V1_92__Drop_update_block_latency_procedure.sql
service/src/main/kotlin/io/provenance/explorer/domain/entities/Blocks.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/ScheduledTaskService.kt
service/src/main/kotlin/io/provenance/explorer/web/v2/ValidatorControllerV2.kt

This PR removes the `block_latency` calculation logic from both the Kotlin code and the PostgreSQL stored procedure. The reason for this removal is that calculating latencies for large ranges of blocks would cause the process to run for hours without completing, which halted block collection.
1. **Removed `block_latency` calculation**: The stored procedure `update_block_latency()` and all references to `block_latency` in the Kotlin code have been removed.
2. **Code cleanup**: Simplified queries and removed unnecessary logic that dealt with `block_latency`.
By removing this, we avoid performance issues that were affecting block collection, especially when handling large datasets.
closes: #XXXX
---
checked …

Remove update block latency procedure call

---

.github/workflows/docker.yml
CHANGELOG.md

This PR updates the Docker workflow to ensure that the `latest` tag in the Docker repository correctly represents the code from the `main` branch, removing the previous behavior of appending a run number to the tag (e.g., `latest-<run-number>`). The outdated `latest` tag was causing issues with ArgoCD, which was attempting to pull the most recent `latest` image but instead retrieved the outdated tag, leading to deployment problems. 
closes: #XXXX
---

Modify workflow to not append the `run-number` to `latest` docker tag

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/ScheduledTaskService.kt

Refactor account processing implementation to be more efficient

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/domain/entities/Markers.kt

This PR modifies the asset pricing update logic by ensuring the `data` column is set to `null` on update or insert. Previously, the `data` column contained the json response from the figure pricing service, which is no longer necessary since data now comes from the Flow API. By nullifying the `data` column, we remove this outdate content. 
This column will be removed completely in the future: https://github.com/provenance-io/explorer-service/issues/563
closes: #XXXX
---

Set asset pricing data column to null on updates from flow grpc

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/config/ExplorerProperties.kt
service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
service/src/main/kotlin/io/provenance/explorer/service/CacheService.kt
service/src/main/kotlin/io/provenance/explorer/service/ExplorerService.kt
service/src/main/kotlin/io/provenance/explorer/service/ValidatorService.kt
service/src/main/kotlin/io/provenance/explorer/service/async/ScheduledTaskService.kt
service/src/main/resources/application-container.properties
service/src/main/resources/application-development.properties
service/src/test/kotlin/io/provenance/explorer/service/ExplorerServiceTest.kt
service/src/test/resources/application-test.properties

This PR removes the spotlight statistics storage in the database. Initially, it was designed as an insert-and-replace cache, later switched to append-only with [PR #221](https://github.com/provenance-io/explorer-service/issues/221). That approach aimed to retain historical data, but this can be aggregated from other tables, and the current design does not process every block, leaving gaps. We can remove the spotlight table in a future release, as it now holds millions of unnecessary records.
closes: #532
---

Remove spotlight from caching to the database

---

CHANGELOG.md
database/src/main/resources/db/migration/V1_94__Drop_spotlight_cache_table.sql

This PR removes the `spotlight_cache` table.  The table was replaced for in memory caching in PR #559 
closes: #XXXX
---

Drop spotlight cache table

---

.github/workflows/publish.yml

Missed updating to jdk 21 for the publish process of the main branch.

- update to java 21

---

CHANGELOG.md
service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt

* Use 3 decimals for `metadata` NAV events when calculating USD value
* Get the exchange module-based price when valuing committed assets and
ensure denom metadata is used to calculate the denom's volume. 
* Re-ordered priv/pub functions in Pulse service
---

Pulse Asset Value Calculation Tweaks, Mild Code Reformatting

---

CHANGELOG.md
RELEASE_CHANGELOG.md
database/src/main/resources/db/migration/V1_100__add_block_show_error.sql
database/src/main/resources/db/migration/V1_101__update_int_PK_columns.sql
service/src/main/kotlin/io/provenance/explorer/domain/entities/Transactions.kt

The tx_msg_event_attr table uses an INT primary key column with a sequence. The number of rows exceeded the max integer value (2.17B) and the sequence nextval is puking. This converts the INT to BIGINT in the PK and seq.

Fix Msg Event Attr Table Integer Overflow

---

service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt

Backfill date needs to use the end-of-day time instead of start-of-day otherwise certain metric events (tx count) are missed for the day.
closes: #607 
---

Fix Backfill Datetime to End-of-Day

---

service/src/main/kotlin/io/provenance/explorer/domain/entities/ExplorerCache.kt
service/src/main/kotlin/io/provenance/explorer/service/PulseMetricService.kt
service/src/main/kotlin/io/provenance/explorer/web/pulse/PulseMetricController.kt

add endpoint to pulse controller to query pulse cache for a type and date range

Pulse Cache History

---

service/src/main/kotlin/io/provenance/explorer/grpc/extensions/Domain.kt
service/src/main/kotlin/io/provenance/explorer/service/AccountService.kt

There's no need for the huge query to determine vesting account initialization - it was causing OOM errors for continuously vesting accounts (of which we have hundreds now).
---

Fix Vesting Account OOM

---

service/src/main/kotlin/io/provenance/explorer/web/v3/AccountControllerV3.kt

We updated the default vesting period to MONTH due to performance issues. With that fixed, we can revert this back to DAY.

Change default vesting period back to DAY
